import type { Metadata } from "next";
import {
  Inter,
  Pixelify_Sans,
  Roboto_Mono,
  Roboto_Condensed,
} from "next/font/google";
import doto from "next/font/local";
import { Analytics } from "@vercel/analytics/next";

import "./globals.css";

const dotoFont = doto({
  src: "./fonts/doto.ttf",
  variable: "--font-doto",
  weight: "400",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const pixelifySans = Pixelify_Sans({
  subsets: ["latin"],
  variable: "--font-pixelify",
  weight: ["400", "500", "600", "700"],
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  variable: "--font-roboto-condensed",
  weight: ["100", "300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${pixelifySans.variable} ${robotoMono.variable} ${robotoCondensed.variable} ${dotoFont.variable} 
           antialiased selection:bg-purple-700 selection:text-purple-100 bg-black selection:font-pixelify`}
      >
        <Analytics />
        {children}
      </body>
    </html>
  );
}
